### ISSUE TITLE
鼠标指针悬浮时，较宽图片无法完整显示

### ISSUE THREAD

**Issue by triplepiers** [AnyaReese/iGEM2025-WP2#2]
sorry 我又来报小 bug 了，不修也没啥关系来着

## 问题描述

原宽度占 `content` 元素 100% 的图片在鼠标指针 hover 放大后会被裁切，导致圆角矩形惨变矩形

以 `Dry Lab/Hardware` 下的 'Circuit diagram of the cell activity detection system' 为例：

<img width="857" alt="Image" src="https://github.com/user-attachments/assets/cf462b93-1a91-4709-807e-e0493a6f9ef1" />

另外，由于左侧有一定 padding，在页面较窄时存在右侧单独被裁切的情况

<img width="583" alt="Image" src="https://github.com/user-attachments/assets/53490db4-ddd8-416b-acff-47f8a1e25bd0" />

## 问题原因

```css
// ./static/css/pages.css 
/* Content area */
.content {
    ...
    overflow: hidden; // line 219
}
```

总之是 `content` 设置了溢出时 hidden，导致经过 `scale(1.02)` 放大后的图片被部分裁剪了

## 可能的解决方案

❓ 把 `figure img` 的最大宽度限制成下面这样：
```css
figure img {
    width: 98%; //  100% / 1.02
}
```

但是

- 在 `max-width: 800px` 的情形下可能还会 bug

    => 可以同步修改成 `max-width: calc(800px / 1.02)` 之类的

- `scale` 变化的形变中心位置可能会偏移（也可能不会 orz）

**Comment by AnyaReese** [comment]
修改了，感谢抓 bug，截断问题没有了，不过图片水平侧的 `box-shadow` 会被截断，应该不影响阅读

```css
figure img {
    /* 98% = 100% / 1.02 */
    width: 98%; 
    max-width: calc(800px / 1.02);
    ...
}
```
